---
title: "pilot analyses"
format: html
editor: source
---

```{r}
library(jsonlite)
library(here)
library(glue)
library(redivis)
library(patchwork)
library(tidyverse)
library(ggrepel)

theme_set(theme_bw() +
            theme(panel.grid = element_blank()))
```

```{r}
task_relabel <- c(
  "egma-math" = "Math",
  "matrix-reasoning" = "Pattern matching",
  "mental-rotation" = "Shape rotation",
  "theory-of-mind" = "Theory of mind",
  "trog" = "Sentence understanding",
  "vocab" = "Vocabulary"
)
```

```{r}
MOD_CLS_SCALE <- c(
  "Human" = "#fa2828",
  "SmolVLM 2" = "#dbaa18",
  "Qwen 3.5" = "#acbf19",
  "TinyLLaVA" = "#19bf4e",
  "InternVL 3.5" = "#19bcbf",
  "Gemma 4" = "#2e65f0",
  "Gemini 2.5 Pro" = "#712ef0",
  "GPT 5.3" = "#d92ef0"
)

MOD_NAM_SCALE <- c(
  "SmolVLM 2 256M" = "#eddba6",
  "SmolVLM 2 500M" = "#e6c76c",
  "SmolVLM 2 2.2B" = "#dbaa18",
  "Qwen 3.5 0.8B" = "#e3ed95",
  "Qwen 3.5 2B" = "#d3e356",
  "Qwen 3.5 4B" = "#acbf19",
  "Qwen 3.5 9B" = "#768509",
  "Qwen 3.5 27B" = "#4b5403",
  "TinyLLaVA 3.1B" = "#19bf4e",
  "InternVL 3.5 1B" = "#96e9eb",
  "InternVL 3.5 2B" = "#62e1e3",
  "InternVL 3.5 4B" = "#19bcbf",
  "InternVL 3.5 8B" = "#0a9294",
  "InternVL 3.5 14B" = "#036466",
  "InternVL 3.5 38B" = "#013c3d",
  "Gemma 4 E2B" = "#799bf2",
  "Gemma 4 E4B" = "#2e65f0",
  "Gemma 4 A4B" = "#0a3194",
  "Gemma 4 31B" = "#031b59",
  "Gemini 2.5 Pro" = "#712ef0",
  "GPT 5.3" = "#d92ef0"
)
```


```{r}
manifest <- read_csv(here("data", "assets", "manifest.csv")) |> 
  filter(task_id != "sds") |> 
  mutate(item_uid = ifelse(
    row_number() >= 241 & row_number() <= 255,
    str_c(item_uid, "b"),
    item_uid
  )) |> 
  distinct()
models <- googlesheets4::read_sheet(ss = "1T3DZzlBDuSFQrZwmby-IZ4Oi2s_7JBffQeoM1bwegJc",
                          sheet = "model_info") |> 
  write_csv(here("data", "model_info.csv"))
```

```{r}
results_files <- list.files(here("results", "v1"), 
                            pattern = "*.csv$", 
                            recursive = TRUE) |> 
  str_subset("(summary|checkpoint|by-type|-tl/)", negate = TRUE)

all_results <- results_files |> 
  map(\(f) {
    if (str_detect(f, "append_resampling")) return(NULL)
    df <- read_csv(here("results", "v1", f), show_col_types = FALSE) |> 
        mutate(filepath = f, reason = as.character(reason))
    ns <- which(df$item_uid == "ns-num-comp-10")
    if (length(ns) == 0) return(df)
    df |> 
      mutate(item_uid = ifelse(
        row_number() > ns,
        str_c(item_uid, "b"),
        item_uid
      ))
    }) |> 
  list_rbind() |> 
  filter(!str_detect(trial_id, "synthetic"))

all_results_join_full <- all_results |> 
  mutate(model = filepath |> str_remove("(-es|-de)?/.*"),
         run_id = filepath |> str_extract("(?<=/).*(?=/)"),
         language = case_when(
                 str_detect(filepath, "-es/") ~ "es",
                 str_detect(filepath, "-de/") ~ "de",
                 .default = "en"
               )) |> 
  left_join(manifest, by = join_by(item_uid)) |> 
  left_join(models, by = join_by(model)) |> 
  mutate(n_params_num = map_dbl(n_params, \(n) {
    suffix = str_sub(n, -1, -1)
    (as.numeric(str_sub(n, 1, -2)) * case_when(
      suffix == "M" ~ 10^6,
      suffix == "B" ~ 10^9,
      suffix == "T" ~ 10^12
    ))
  })) |> 
  filter(!is.na(model_name),
         !is.na(run_id),
         !str_detect(model_class, "Molmo"),
         model_name != "TinyLLaVA 2.4B")

all_results_join <- all_results_join_full |> 
  filter(language == "en")
```

```{r}
json_files <- list.files(here("results", "v1"), 
                            pattern = "*responses.json$", 
                            recursive = TRUE) |> 
  str_subset("-tl/", negate = TRUE)

all_json <- map(json_files, \(f) {
  json <- read_json(here("results", "v1", f), simplifyVector = TRUE)
  synthetic <- map_lgl(json, \(j) str_detect(j$trial_id, "synthetic"))
  df <- json[!synthetic] |> 
    as_tibble() |> t() |> 
    as_tibble(rownames = "trial_unique",
              .name_repair = "universal_quiet") |> 
    `colnames<-`(value = c("trial_unique", json[[1]] |> names())) |> 
    mutate(filepath = f)
}) |> list_rbind() |> 
  mutate(model = filepath |> str_remove("(-es|-de)?/.*"),
         run_id = filepath |> str_extract("(?<=/).*(?=/cache)")) |> 
  filter(run_id != "cache")

all_json_opt_full <- all_json |> 
  mutate(chosen_option = map2_chr(options, predicted_label, \(opts, l) {
    if (is.null(l)) return(NA)
    idx <- str_locate("ABCD", l)[1]
    opts[idx]
  })) |> 
  unnest(where(is.list) & !starts_with("option")) |> 
  mutate(language = case_when(
                 str_detect(filepath, "-es/") ~ "es",
                 str_detect(filepath, "-de/") ~ "de",
                 .default = "en"
               )) |> 
  left_join(manifest, by = join_by(item_uid)) |> 
  left_join(models, by = join_by(model)) |> 
  mutate(n_params_num = map_dbl(n_params, \(n) {
    suffix = str_sub(n, -1, -1)
    (as.numeric(str_sub(n, 1, -2)) * case_when(
      suffix == "M" ~ 10^6,
      suffix == "B" ~ 10^9,
      suffix == "T" ~ 10^12
    ))
  })) |> 
  filter(!is.na(model_name),
         !is.na(run_id),
         !str_detect(model_class, "Molmo"),
         model_name != "TinyLLaVA 2.4B") |> 
  mutate(item_uid = ifelse(item_uid == "math_compare_7_5" & map_lgl(options, \(o) 8 %in% o),
                           "math_compare_7_5b", item_uid))

all_json_opt <- all_json_opt_full |> 
  filter(language == "en")
```

```{r}
clean_uid <- function(item_uid, task_id) {
  item_uid <- str_replace(item_uid, "_word_", "__")
  if (is.na(task_id)) return(item_uid)
  item_uid <- ifelse(task_id == "mrot", str_remove(item_uid, "-.*"), item_uid)
  item_uid <- ifelse(task_id == "tom", str_remove(item_uid, "story[0-9]_"), item_uid)
  item_uid <- ifelse(task_id == "tom", str_replace(item_uid, "-2", "_"), item_uid)
  item_uid <- replace_values(
    item_uid,
    "tom_moral_reasoning_reality_check_1" ~ "tom_moral_reasoning_reality_check",
    "tom_moral_reasoning_false_belief_3" ~ "tom_moral_reasoning_false_belief",
    "math_fraction_14_24_34" ~ "math_fraction_14_24",
    "math_fraction_13_23_1" ~ "math_fraction_13_23",
    "math_fraction_16_13_12" ~ "math_fraction_16_13",
    "math_fraction_17_314_514" ~ "math_fraction_17_314",
    "math_fraction_512_16_712" ~ "math_fraction_512_16",
    "math_fraction_39_13_23" ~ "math_fraction_39_13",
    "math_fraction_48_18_38" ~ "math_fraction_48_18",
    "math_fraction_710_25_310" ~ "math_fraction_710_25",
    "math_fraction_13_17_421" ~ "math_fraction_13_17",
    "math_fraction_512_16_14" ~ "math_fraction_512_16s",
    "math_fraction_19_110_190" ~ "math_fraction_19_110",
    "math_fraction_178_54_78" ~ "math_fraction_178_54",
    "math_fraction_12_13_16" ~ "math_fraction_12_13",
    "math_fraction_34_716_516" ~ "math_fraction_34_7_16",
    "math_fraction_28_39_712" ~ "math_fraction_28_39"
  )
  item_uid
}

normalise_options <- function(options) {
  options |> 
    as.character() |> 
    str_remove_all("-") |> 
    str_to_lower()
}

kl_divergence <- function(p, q, epsilon = 1e-12) {
  p <- as.numeric(p)
  q <- as.numeric(q)
  
  # add epsilon for numerical stability
  p <- p + epsilon
  q <- q + epsilon
  
  # renormalize
  p <- p / sum(p)
  q <- q / sum(q)
  
  sum(p * log(p / q))
}
```


# Accuracy
```{r}
all_results_summary <- all_results_join |> 
  group_by(task, model_class, model_name, n_params_num, run_id) |> 
  summarise(accuracy = mean(is_correct),
            chance = mean(chance_level, na.rm = T),
            .groups = "drop")
```

```{r}
all_results_total <- all_results_join |> 
  group_by(model_class, model_name, n_params_num, task) |> 
  summarise(accuracy = mean(is_correct),
            chance = mean(chance_level, na.rm = T),
            .groups = "drop_last") |> 
  summarise(accuracy = mean(accuracy),
            chance = mean(chance, na.rm = T),
            .groups = "drop")
```

```{r}
all_results_total |> 
  ggplot(aes(x = log10(n_params_num), y = accuracy, col = model_class)) +
  geom_line() +
  geom_point()
```

```{r}
gpt_results <- all_results_summary |> 
  filter(model_name == "GPT 5.3") |> 
  group_by(task) |> 
  summarise(accuracy = mean(accuracy)) |> 
  arrange(desc(accuracy))

all_results_bymodel <- all_results_summary |> 
  group_by(model_class, model_name, n_params_num, task) |> 
  summarise(accuracy = mean(accuracy), 
            n_runs = n(),
            .groups = "drop") |> 
  mutate(task = fct_relevel(task, gpt_results$task))

p_acc <- all_results_summary |> 
  mutate(task = fct_relevel(task, gpt_results$task)) |> 
  ggplot(aes(x = log10(n_params_num), y = accuracy)) +
  geom_smooth(aes(group = "none"), 
              data = all_results_bymodel,
              method = "glm", formula = y ~ x,
              method.args = list(family = "binomial"), 
              lty = "dashed", se = F, col = "black") +
  geom_hline(aes(yintercept = chance), lty = "dotted", col = "grey54") +
  geom_line(aes(col = model_class), 
            data = all_results_bymodel) +
  stat_summary(aes(col = model_class, group = model_name),
               fun.data = mean_cl_boot, size = 0.2) +
  # geom_point(aes(col = model_class)) +
  facet_wrap(~ task,
             labeller = as_labeller(task_relabel)) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_colour_manual(values = MOD_CLS_SCALE,
                      limits = setdiff(names(MOD_CLS_SCALE), "Human")) +
  labs(x = "Log parameters",
       y = "Accuracy",
       col = "Model class")

ggsave(here("figs", "accuracy.png"), p_acc,
       width = 7, height = 4, units = "in")

p_acc
```

# Item parameters
```{r}
item_params <- list.files(here("data", "responses", "v1", "irt_models"),
                          pattern = "_item_params.csv",
                          full.names = T) |> 
  map(\(f) {
    df <- read_csv(f, show_col_types = F)
    if (str_detect(f, "mental-rotation")) {
      df2 <- df |> 
        mutate(item_uid = item_uid |> 
                 str_replace_all(c(
                   "020" = "340",
                   "040" = "320",
                   "080" = "280",
                   "120" = "240",
                   "160" = "200"
                 )))
      df <- bind_rows(df, df2)
    }
    df
  }) |> 
  list_rbind() |> 
  mutate(task_id = str_remove(item_uid, "_.*"),
         item_uid = map2_chr(item_uid, task_id, clean_uid)) |> 
  distinct()
```

```{r}
all_results_difficulty <- all_results_join |> 
  mutate(item_uid_orig = item_uid,
         item_uid = ifelse(task_id == "mrot", str_remove(item_uid, "(?<=[0-9]{3})_.*"), item_uid)) |> 
  left_join(item_params, by = join_by(task_id, item_uid)) |> 
  mutate(is_correct = as.numeric(is_correct))
```

```{r}
all_results_difficulty |> 
  ggplot(aes(x = difficulty, y = is_correct, col = model_name)) +
  geom_point(alpha = .01) +
  geom_smooth(aes(group = model_name), 
              method = "glm", method.args = list(family = "binomial"),
              se = F) +
  facet_wrap(~ task) +
  labs(x = "Difficulty",
       y = "Accuracy",
       col = "Model")
```

```{r}
cor_results <- all_results_difficulty |> 
  group_by(task, model_name, model_class, n_params_num, run_id) |> 
  summarise(cor = cor(is_correct, difficulty, use = "pairwise.complete.obs"),
            .groups = "drop") |> 
  mutate(task = fct_relevel(task, gpt_results$task))

cor_summary <- cor_results |> 
  group_by(task, model_name, model_class, n_params_num) |> 
  summarise(cor = mean(cor),
            .groups = "drop") |> 
  mutate(task = fct_relevel(task, gpt_results$task))
```

```{r}
p_corr <- cor_results |> 
  ggplot(aes(x = log10(n_params_num), y = cor)) +
  geom_hline(yintercept = 0, lty = "dotted", col = "grey54") +
  geom_smooth(aes(group = "none"), 
              method = "lm", formula = y ~ x,
              data = cor_summary,
              lty = "dashed", se = F, col = "black") +
  geom_line(aes(col = model_class),
            data = cor_summary) +
  # geom_point(aes(col = model_class)) +
  stat_summary(aes(col = model_class, group = model_name),
               fun.data = mean_cl_boot, size = 0.2) +
  facet_wrap(~ task,
             labeller = as_labeller(task_relabel)) +
  # coord_cartesian(ylim = c(-.5, .5)) +
  scale_colour_manual(values = MOD_CLS_SCALE,
                      limits = setdiff(names(MOD_CLS_SCALE), "Human")) +
  labs(x = "Log parameters",
       y = "Accuracy-item easiness correlation",
       col = "Model class")

ggsave(here("figs", "item_cor.png"), p_corr,
       width = 7, height = 4, units = "in")

p_corr
```

# Task difficulty
Recover run_id to user_id mapping
```{r}
id_link <- list.files(here("data", "responses", "v1", "tasks"),
                             pattern = "_trials.csv",
                             full.names = T) |> 
  map(\(f) {
    read_csv(f, show_col_types = F) |> 
      select(task = task_id, user_id, run_id, age, site) |> 
      distinct()
  }) |> 
  list_rbind()

ability_scores <- list.files(here("data", "responses", "v1", "irt_models"),
                             pattern = "ability_scores.csv",
                             full.names = T) |> 
  map(\(f) {
    read_csv(f, show_col_types = F)
  }) |> 
  list_rbind()

ability_ids <- id_link |> 
  left_join(ability_scores, by = join_by(run_id)) |> 
  filter(!is.na(ability))
```

First, estimate performance for all participants
```{r}
full_item_params <- list.files(here("data", "responses", "v1", "irt_models"),
                             pattern = ".rds",
                             full.names = T) |> 
  map(\(f) (readRDS(f))@model_vals |> 
        mutate(task = str_remove(f, ".*/") |> str_remove(".rds"),
               item = str_remove(item, "-1$"))) |> 
  list_rbind() |> 
  select(task, item, name, value) |> 
  filter(item != "GROUP") |> 
  rename(item_uid = item) |> 
  pivot_wider(names_from = "name",
              values_from = "value",
              values_fn = unique) |> 
  mutate(task_id = str_remove(item_uid, "_.*"),
         item_uid = str_replace(item_uid, "_word_", "__"),
         item_uid = ifelse(task_id == "mrot", str_remove(item_uid, "-.*"), item_uid),
         item_uid = ifelse(task_id == "tom", str_remove(item_uid, "story[0-9]_"), item_uid),
         item_uid = ifelse(task_id == "tom", str_replace(item_uid, "-2", "_"), item_uid),
         #task = str_replace(task, "downex", "egma")
         ) |> 
  distinct() |> 
  filter(!str_detect(task, "downex"))
```

```{r}
item_by_group <- full_item_params |> 
  nest(items = -c(task)) |> 
  left_join(ability_ids |> 
              nest(abilities = -c(task)),
            by = join_by(task))
```

```{r}
calc_prob_4pl <- function(theta, a1, d, g, u) {
  b <- d / a1
  g + (u - g) / (1 + exp(-a1 * (theta - b)))
}

included_items <- all_results_difficulty |> 
  distinct(item_uid) |> 
  pull(item_uid)

item_by_group_cross <- item_by_group |> 
  mutate(est_scores = map2(items, abilities, \(it, ab) {
    full_data <- cross_join(it, ab) |> 
      filter(item_uid %in% included_items) |> 
      mutate(prob = pmap_dbl(list(ability, a1, d, g, u), calc_prob_4pl))
  }))

est_sumscores <- item_by_group_cross |> 
  mutate(sumscores = map(est_scores, \(s) {
    s |> group_by(run_id) |> 
      summarise(sumscore = sum(prob),
                n_trials = n(),
                accuracy = sumscore / n_trials)
  })) |> 
  select(task, sumscores) |> 
  unnest(sumscores) |> 
  left_join(ability_ids, by = join_by(task, run_id))
```

```{r}
est_sumscores |> 
  mutate(task = fct_reorder(task, accuracy)) |> 
  ggplot(aes(x = task, y = accuracy)) +
  geom_point(alpha = .05, position = position_jitter(width = .4, seed = 123)) +
  stat_summary(aes(col = model_name), data = all_results_summary, fun.data = mean_cl_boot) +
  # geom_point(aes(col = model_name), data = all_results_summary) +
  geom_line(aes(col = model_name, group = model_name), 
            data = all_results_summary |> 
              group_by(model_name, task) |> 
              summarise(accuracy = mean(accuracy, na.rm = T), .groups = "drop")) +
  labs(x = "Task", y = "Accuracy")
```

```{r}
est_sumscores |> 
  group_by(user_id, task) |> 
  summarise(n = n(), .groups = "drop_last") |> 
  summarise(n = n()) |> 
  ggplot(aes(x = n)) +
  geom_histogram() +
  labs(x = "Number of tasks", y = "Count")
```

```{r}
human_est <- est_sumscores |> 
  group_by(task) |> 
  summarise(accuracy = mean(accuracy, na.rm = T))
```

```{r eval=F}
p_task <- all_results_summary |> 
  left_join(human_est |> rename(human_accuracy = accuracy), by = join_by(task)) |> 
  ggplot(aes(x = human_accuracy, y = accuracy, col = model_name)) +
  geom_abline(intercept = 0, slope = 1, lty = "dashed", col = "grey54") +
  geom_point(aes(shape = task)) +
  geom_smooth(method = "lm", se = F) +
  # geom_line() +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  labs(x = "Human task accuracy", y = "Model task accuracy",
       col = "Model", shape = "Task") +
  theme(legend.box = "horizontal")

p_task
```

```{r}
human_splithalf <- tibble(run = 1:1000) |> 
  mutate(corr = map(run, \(r) {
    set.seed(r)
    est_sumscores |> 
      nest(data = -user_id) |> 
      mutate(split = sample(2, n(), replace = T)) |> 
      unnest(data) |> 
      group_by(task, split) |> 
      summarise(accuracy = mean(accuracy, na.rm = T),
                .groups = "drop") |> 
      pivot_wider(names_from = split, values_from = accuracy,
                  names_prefix = "split_") |> 
      summarise(human_sh_r = cor(split_1, split_2, use = "pairwise.complete.obs"),
                human_sh_rho = cor(split_1, split_2, 
                                   use = "pairwise.complete.obs", method = "spearman"))
  })) |> 
  unnest(corr)

all_summary <- all_results_join |> 
  filter(item_uid %in% (all_results_difficulty |> filter(!is.na(difficulty)) |> pull(item_uid))) |> 
  group_by(task, model_class, model_name, n_params_num, run_id) |> 
  summarise(accuracy = mean(is_correct),
            chance = mean(chance_level, na.rm = T),
            .groups = "drop")

mh_cors <- all_summary |> 
  left_join(human_est |> rename(human_accuracy = accuracy), by = join_by(task)) |> 
  group_by(model_class, model_name, n_params_num, run_id) |> 
  summarise(model_human_r = cor(accuracy, human_accuracy, use = "pairwise.complete.obs"),
            model_human_rho = cor(accuracy, human_accuracy, 
                                  use = "pairwise.complete.obs", method = "spearman"),
            .groups = "drop") # |> 
  # bind_rows(human_splithalf |> 
  #             summarise(model_human_r = mean(human_sh_r),
  #                       model_human_rho = mean(human_sh_rho)) |> 
  #             mutate(model_class = "Human", model_name = "Human"))
```


```{r}
df_task_rank <- all_results_summary |> 
  group_by(model_class, model_name, n_params_num, task) |> 
  summarise(accuracy = mean(accuracy, na.rm = T),
            chance = mean(chance, na.rm = T),
            .groups = "drop_last") |> 
  bind_rows(human_est |> mutate(model_name = "Human")) |> 
  arrange(desc(accuracy)) |> 
  mutate(task_rank = row_number()) |> 
  ungroup() |> 
  mutate(model_name = factor(model_name) |> fct_reorder(accuracy) |> fct_relevel("Human") |> fct_rev(),
         task = factor(task, levels = human_est |> arrange(desc(accuracy)) |> pull(task)) |> 
           fct_relabel(\(x) {
             replace_values(x,
                            "theory-of-mind" ~ "tom",
                            "matrix-reasoning" ~ "matrix",
                            "mental-rotation" ~ "mrot",
                            "egma-math" ~ "math")
           })) |> 
  group_by(model_name)

p_task_rank <- df_task_rank |> 
  ggplot(aes(x = task, y = model_name, fill = task_rank)) +
  geom_tile() +
  labs(x = "Task", y = "Model", fill = "Task rank") +
  theme(legend.position = "bottom")

p_cors <- mh_cors |> 
  mutate(model_name = factor(model_name, levels = levels(df_task_rank$model_name))) |> 
  pivot_longer(cols = c(model_human_r, model_human_rho),
               names_to = "corr_type",
               values_to = "corr") |> 
  mutate(corr_type = recode_values(corr_type,
                                   "model_human_r" ~ "Pearson's r",
                                   "model_human_rho" ~ "Spearman's rho")) |> 
  ggplot(aes(x = corr_type, y = model_name, fill = corr)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.3f", corr)), size = 3) +
  scale_fill_continuous(palette = c("#DE2D26", "#F0F0F0", "#264bde"),
                        limits = c(-1, 1)) +
  labs(x = "Model-human correlation", y = "Model", fill = "Correlation") +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "bottom")

(p_task_rank + p_cors) # &
  # plot_layout(widths = c(6,2))
```

```{r}
human_sh_ci <- mean_cl_boot(human_splithalf$human_sh_r)

# mod_task_param <- nls(model_human_r ~ SSlogis(log10(n_params_num), Asym, xmid, scal),
#                       data = mh_cors)
# pred_task_param <- tibble(
#   log_n_params_num = seq(log10(min(mh_cors$n_params_num)),
#                          log10(max(mh_cors$n_params_num)),
#                          0.1)
# ) |> mutate(n_params_num = 10^(log_n_params_num))
# pred_task_param <- pred_task_param |> 
#   mutate(model_human_r = predict(fit, newdata = tibble(x = pred_task_param$log_n_params_num)))
# 
# x <- pred_task_param$log_n_params_num
# y <- pred_task_param$model_human_r
# 
# # crude but stable starts from data
# U0  <- quantile(y, 0.95, na.rm=TRUE)   # ~ top plateau
# L0  <- quantile(y, 0.05, na.rm=TRUE)   # ~ bottom plateau
# x00 <- x[which.min(abs(y - (L0 + (U0-L0)/2)))]  # x near half-height
# s0  <- 0.3  # adjust if needed (bigger = less steep)
# 
# log4 <- function(x, L, U, x0, s) L + (U - L) / (1 + exp((x - x0)/s))
# 
# fit <- nls(y ~ log4(x, L, U, x0, s),
#            start = list(L=-0.5, U=1, x0=x00, s=1),
#            algorithm = "port",
#            lower = c(L=-1.5, U= 1, x0=min(x), s=1e-6),
#            upper = c(L= 0.5, U= 1.5, x0=max(x), s=100))
# 
# coef(fit)
```


```{r}
mh_cors_summary <- mh_cors |> 
  group_by(model_class, model_name, n_params_num) |> 
  summarise(model_human_r = mean(model_human_r, na.rm = T),
            model_human_rho = mean(model_human_rho, na.rm = T),
            .groups = "drop") |> 
  left_join(all_summary |> 
              group_by(model_name, run_id) |> 
              summarise(accuracy = mean(accuracy), .groups = "drop_last") |> 
              summarise(accuracy = mean(accuracy)),
            by = join_by(model_name))

p_tasks <- mh_cors |> 
  ggplot(aes(x = log10(n_params_num))) +
  geom_hline(yintercept = 0, lty = "dotted", col = "grey54") +
  annotate(geom = "rect",
           ymin = human_sh_ci$ymin, ymax = human_sh_ci$ymax, 
           xmin = 7, xmax = 13, col = "#f5b3b3") +
  geom_hline(yintercept = mean(human_splithalf$human_sh_r), lty = "dashed", col = "#fa2828") +
  annotate(geom = "text",
           x = 12.2, y = 0.9, label = "Human split-half", hjust = 1,
           col = "#fa2828") +
  # geom_dotplot(col = "white", binwidth = .05, method = "histodot",
  #              stackgroups = T)
  # geom_line(aes(y = model_human_r), data = pred_task_param,
  #           lty = "dashed") +
  stat_summary(aes(y = model_human_r, col = model_class, group = model_name),
               fun.data = mean_cl_boot, size = 0.2) +
  # geom_point(aes(y = model_human_r, col = model_class)) +
  geom_line(aes(y = model_human_r, col = model_class),
            data = mh_cors_summary) +
  coord_cartesian(xlim = c(8.2, 12.4)) +
  scale_colour_manual(values = MOD_CLS_SCALE,
                      limits = setdiff(names(MOD_CLS_SCALE), "Human")) +
  labs(x = "Log parameters", y = "Model-human\ntask accuracy correlation", col = "Model class") +
  theme(legend.position = "none")

mh_acc <- mh_cors |> 
  left_join(all_summary |> 
              group_by(model_name, run_id) |> 
              summarise(accuracy = mean(accuracy), .groups = "drop"),
            by = join_by(model_name, run_id))

p_task_acc <- mh_acc |> 
  ggplot(aes(x = accuracy)) +
  geom_hline(yintercept = 0, lty = "dotted", col = "grey54") +
  annotate(geom = "rect",
           ymin = human_sh_ci$ymin, ymax = human_sh_ci$ymax, 
           xmin = -0.8, xmax = 1.2, col = "#f5b3b3") +
  geom_hline(yintercept = mean(human_splithalf$human_sh_r), lty = "dashed", col = "#fa2828") +
  annotate(geom = "text",
           x = 0.86, y = 0.9, label = "Human split-half", hjust = 1,
           col = "#fa2828") +
  # geom_dotplot(col = "white", binwidth = .05, method = "histodot",
  #              stackgroups = T)
  stat_summary(aes(y = model_human_r, col = model_class, group = model_name),
               geom = "errorbar", orientation = "x",
               fun.data = mean_cl_boot,
               data = mh_acc |> 
                 group_by(model_class, model_name) |> 
                 mutate(accuracy = mean(accuracy))) +
  stat_summary(aes(y = model_human_r, col = model_class, group = model_name),
               geom = "errorbar", orientation = "y",
               fun.data = mean_cl_boot,
               data = mh_acc |> 
                 group_by(model_class, model_name) |> 
                 mutate(model_human_r = mean(model_human_r))) +
  geom_point(aes(y = model_human_r, col = model_class),
             data = mh_cors_summary) +
  # geom_point(aes(y = model_human_r, col = model_class)) +
  geom_line(aes(y = model_human_r, col = model_class),
            data = mh_cors_summary) +
  coord_cartesian(xlim = c(0.24, 0.89)) +
  scale_colour_manual(values = MOD_CLS_SCALE,
                      limits = setdiff(names(MOD_CLS_SCALE), "Human")) +
  labs(x = "Accuracy", y = "Model-human\ntask accuracy correlation", col = "Model class")

p_task_out <- (p_tasks | p_task_acc) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A")

ggsave(here("figs", "task_cor.png"), p_task_out,
       width = 7, height = 2.8, units = "in")

p_task_out
```


# Leaderboard
```{r}
grand_summary <- est_sumscores |> 
  mutate(age_bin = floor(age)) |> 
  group_by(age_bin, task) |> 
  summarise(accuracy = mean(accuracy, na.rm = T),
            .groups = "drop_last") |> 
  summarise(accuracy = mean(accuracy, na.rm = T),
            .groups = "drop") |> 
  filter(!is.na(age_bin),
         age_bin <= 12)
```

```{r}
all_accuracy <- bind_rows(
  all_results_total,
  grand_summary |> 
    mutate(model_class = "Human",
           model_name = str_c(age_bin, "-year-olds")) |> 
    select(-age_bin)
) |> 
  arrange(desc(accuracy)) |> 
  mutate(model_name = fct_reorder(model_name, accuracy),
         model_class = fct_relevel(model_class, "Human"))
```

```{r}
all_accuracy |> 
  ggplot(aes(x = accuracy, y = model_name, fill = model_class)) +
  geom_col() +
  labs(x = "Accuracy", y = "", fill = "")
```

```{r}
p_leader <- all_accuracy |> 
  ggplot(aes(x = 1, y = accuracy, col = model_class)) +
  geom_point() +
  geom_text_repel(aes(label = model_name), 
                  size = 2.5,
                  xlim = c(1.01, NA),
                  hjust = 0,
                  force = 2,
                  direction = "y",
                  min.segment.length = 0) +
  coord_cartesian(xlim = c(0.999, 1.021)) +
  labs(x = "", y = "Accuracy") +
  scale_colour_manual(values = MOD_CLS_SCALE,
                      limits = names(MOD_CLS_SCALE)) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave(here("figs", "leaderboard.png"), p_leader,
       width = 2.5, height = 5, units = "in")

p_leader
```


# Response distributions
```{r}
option_keys <- list.files(here("data", "responses", "v1", "responses_by_ability"), 
                            pattern = "*option_key.csv$") |> 
  map(\(f) {
    read_csv(here("data", "responses", "v1", "responses_by_ability", f), 
                    show_col_types = F) |> 
      mutate(task_id = f |> str_remove("_.*"))
    }) |> 
  list_rbind() |> 
  mutate(item_uid = map2_chr(item_uid, task_id, clean_uid)) |> 
  pivot_longer(cols = starts_with("image"),
               names_to = "image",
               values_to = "chosen_option") |> 
  mutate(chosen_option = normalise_options(chosen_option),
         item_uid = ifelse(task_id == "mental-rotation", 
                           glue("{item_uid}_{item_original}"), 
                           item_uid)) |> 
  filter(!is.na(chosen_option),
         item_original != "rubberband") |> 
  distinct()

distribs <- list.files(here("data", "responses", "v1", "responses_by_ability"), 
                            pattern = "*proportions_by_ability.csv$") |> 
  map(\(f) read_csv(here("data", "responses", "v1", "responses_by_ability", f), 
                    show_col_types = F)) |> 
  list_rbind() |> 
  pivot_longer(cols = starts_with("image"),
               names_to = "image",
               values_to = "prop") |> 
  mutate(task_id = str_remove(item_uid, "_.*"),
         item_uid = map2_chr(item_uid, task_id, clean_uid))
```

```{r}
model_distribs <- all_json_opt |> 
  group_by(task, item_uid, model_class, model_name, n_params_num, chosen_option) |> 
  summarise(n = n(),
            .groups = "drop_last") |> 
  mutate(runs = sum(n, na.rm = T),
         prop = n / runs,
         item_uid = ifelse(task == "mental-rotation", 
                           str_remove(item_uid, "-") |> str_to_lower(),
                           item_uid),
         chosen_option = normalise_options(chosen_option),
         item_uid = map2_chr(item_uid, task, \(u, t) clean_uid(u, t)))

model_distribs_opts <- model_distribs |> 
  left_join(option_keys, by = join_by(task == task_id, item_uid, chosen_option))
```

```{r}
model_human_distribs <- model_distribs_opts |> 
  mutate(item_uid = ifelse(task == "mental-rotation",
                           item_uid |> str_remove("(?<=[0-9]{3})_.*"),
                           item_uid)) |> 
  group_by(task, item_uid, model_class, model_name, n_params_num, image) |> 
  summarise(n = sum(n, na.rm = T),
            .groups = "drop_last") |> 
  mutate(runs = sum(n, na.rm = T),
            prop_model = n / runs) |> 
  nest(model = -c(task, item_uid, model_class, model_name, n_params_num, runs)) |> 
  left_join(distribs |> rename(prop_human = prop) |> 
              nest(human = -c(item_uid)), 
            by = join_by(item_uid)) |> 
  mutate(mod_hum = map2(model, human, \(m, h) {
    if (is.null(h)) return(NULL)
    full_join(m, h, by = join_by(image)) |> 
      mutate(prop_model = replace_na(prop_model, 0))
  }))

model_human_kl <- model_human_distribs |> 
  mutate(d_kl = map(mod_hum, \(mh) {
    if (is.null(mh)) return(NULL)
    mh |> 
      filter(!is.na(ability_bin)) |> 
      group_by(ability_bin, n_ppts) |> 
      summarise(d_kl = kl_divergence(prop_human, prop_model),
                .groups = "drop")
  })) |> 
  select(task, item_uid, model_class, model_name, n_params_num, runs, d_kl) |> 
  unnest(d_kl)
```

```{r}
kl_summary <- model_human_kl |> 
  filter(n_ppts >= 10) |> 
  group_by(task, model_class, model_name, n_params_num, ability_bin) |> 
  summarise(min_runs = min(runs),
            min_ppts = min(n_ppts), 
            d_kl = mean(d_kl, na.rm = T),
            .groups = "drop")
```

```{r}
p_distrib <- kl_summary |> 
  filter(min_runs >= 10) |> 
  mutate(task = fct_relevel(task, gpt_results$task),
         ability_bin = ability_bin |> str_replace("_", ", "),
         ability_bin = glue("[{ability_bin}]") |> 
           factor(levels = c("[-5, -4]", "[-4, -3]", "[-3, -2]",
                             "[-2, -1]", "[-1, 0]", "[0, 1]",
                             "[1, 2]", "[2, 3]", "[3, 4]", "[4, 5]"))) |>
  ggplot(aes(x = ability_bin, y = d_kl, col = model_name)) +
  geom_line(aes(group = model_name)) +
  geom_point() +
  facet_wrap(~ task,
             labeller = as_labeller(task_relabel)) +
  scale_colour_manual(values = MOD_NAM_SCALE,
                      limits = intersect(names(MOD_NAM_SCALE), 
                                         unique(kl_summary |> 
                                                  filter(min_runs >= 10) |> 
                                                  pull(model_name)))) +
  labs(x = "Ability bin", y = "KL divergence", col = "Model") +
  theme(axis.text.x = element_text(hjust = 1, angle = 45)) +
  guides(colour = guide_legend(ncol = 2))

ggsave(here("figs", "distrib.png"), p_distrib,
       width = 8, height = 4, units = "in")

p_distrib
```

```{r}
kl_summary |> 
  filter(min_runs >= 10) |> 
  mutate(task = fct_relevel(task, gpt_results$task),
         ability_bin = ability_bin |> str_replace("_", ", "),
         ability_bin = glue("[{ability_bin}]") |> 
           factor(levels = c("[-5, -4]", "[-4, -3]", "[-3, -2]",
                             "[-2, -1]", "[-1, 0]", "[0, 1]",
                             "[1, 2]", "[2, 3]", "[3, 4]", "[4, 5]"))) |> 
  ggplot(aes(x = log10(n_params_num), y = d_kl, col = ability_bin)) +
  geom_point() +
  geom_smooth(method = "loess", formula = y ~ x, 
              se = F, span = .8) +
  facet_wrap(~ task,
             labeller = as_labeller(task_relabel)) +
  labs(x = "Log parameters", y = "KL divergence", col = "Ability bin")
```

```{r}
p_kl_param <- kl_summary |> 
  filter(min_runs >= 10,
         task %in% c("egma-math", "trog")) |> 
  mutate(task = fct_relevel(task, gpt_results$task),
         ability_bin = ability_bin |> str_replace("_", ", "),
         ability_bin = glue("[{ability_bin}]") |> 
           factor(levels = c("[-5, -4]", "[-4, -3]", "[-3, -2]",
                             "[-2, -1]", "[-1, 0]", "[0, 1]",
                             "[1, 2]", "[2, 3]", "[3, 4]", "[4, 5]"))) |> 
  ggplot(aes(x = log10(n_params_num), y = d_kl, col = ability_bin)) +
  geom_point() +
  geom_smooth(method = "loess", formula = y ~ x, 
              se = F, span = .9) +
  facet_wrap(~ task,
             labeller = as_labeller(task_relabel)) +
  labs(x = "Log parameters", y = "KL divergence", col = "Ability bin") +
  guides(colour = guide_legend(ncol = 2))

p_kl_ability <- kl_summary |> 
  filter(min_runs >= 10,
         task %in% c("vocab", "matrix-reasoning")) |> 
  mutate(task = fct_relevel(task, gpt_results$task),
         ability_bin = ability_bin |> str_replace("_", ", "),
         ability_bin = glue("[{ability_bin}]") |> 
           factor(levels = c("[-5, -4]", "[-4, -3]", "[-3, -2]",
                             "[-2, -1]", "[-1, 0]", "[0, 1]",
                             "[1, 2]", "[2, 3]", "[3, 4]", "[4, 5]"))) |>
  ggplot(aes(x = ability_bin, y = d_kl, col = model_name)) +
  geom_line(aes(group = model_name)) +
  geom_point() +
  facet_wrap(~ task,
             labeller = as_labeller(task_relabel)) +
  scale_colour_manual(values = MOD_NAM_SCALE,
                      limits = intersect(names(MOD_NAM_SCALE), 
                                         unique(kl_summary |> 
                                                  filter(min_runs >= 10) |> 
                                                  pull(model_name)))) +
  labs(x = "Ability bin", y = "KL divergence", col = "Model") +
  theme(axis.text.x = element_text(hjust = 1, angle = 45)) +
  guides(colour = guide_legend(ncol = 2))

p_distrib_out <- (p_kl_param / p_kl_ability) +
  plot_annotation(tag_levels = "A")

ggsave(here("figs", "distrib_new.png"), p_distrib_out,
       width = 8, height = 5, units = "in")

p_distrib_out
```


# Other langs
```{r}
non_eng_models <- all_results_join_full |> 
  filter(language != "en") |> 
  distinct(model_name)
```

```{r}
all_results_join_compare <- all_results_join_full |> 
  filter(model_name %in% non_eng_models$model_name)

all_results_cmp_wide <- all_results_join_compare |> 
  group_by(task, model_class, model_name, n_params_num, language, run_id) |> 
  summarise(accuracy = mean(is_correct),
            chance = mean(chance_level, na.rm = T),
            .groups = "drop_last") |> 
  group_by(task, model_class, model_name, n_params_num, language) |> 
  summarise(accuracy = mean(accuracy),
            .groups = "drop") |> 
  pivot_wider(names_from = language, values_from = accuracy) |> 
  pivot_longer(cols = c(de, es),
               names_to = "language",
               values_to = "accuracy")
```

```{r}
p_xling <- all_results_cmp_wide |> 
  mutate(task = fct_relevel(task, gpt_results$task)) |> 
  ggplot(aes(x = en, y = accuracy, col = model_name, shape = language)) +
  geom_abline(slope = 1, intercept = 0, lty = "dotted", col = "grey54") +
  geom_point() +
  facet_wrap(~ task,
             labeller = as_labeller(task_relabel)) +
  scale_colour_manual(values = MOD_NAM_SCALE,
                      limits = intersect(names(MOD_NAM_SCALE),
                                         unique(all_results_cmp_wide$model_name))) +
  scale_shape_discrete(labels = c("German", "Spanish")) +
  labs(x = "English accuracy", y = "Other language accuracy", col = "Model", shape = "Language")

ggsave(here("figs", "xling.png"), p_xling,
       width = 7, height = 4, units = "in")

p_xling
```

