#!/usr/bin/env python3
"""Plot model comparison as line chart (tasks on x-axis, accuracy on y-axis)."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot line chart from model-comparison-report.json",
    )
    parser.add_argument(
        "--report-json",
        type=Path,
        default=Path("results/model-comparison-report.json"),
        help="Path to JSON report generated by build_model_comparison_report.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/model-comparison-line-chart.png"),
        help="Output chart path (PNG).",
    )
    parser.add_argument(
        "--min-tasks",
        type=int,
        default=1,
        help="Only include model entries with at least this many tasks (default: 1).",
    )
    return parser.parse_args()


def _task_sort_key(task_id: str) -> tuple[int, str]:
    preferred = [
        "egma-math",
        "matrix-reasoning",
        "mental-rotation",
        "theory-of-mind",
        "trog",
        "vocab",
    ]
    if task_id in preferred:
        return (0, f"{preferred.index(task_id):03d}")
    return (1, task_id)


def _model_label(model: str, size: str | None) -> str:
    return f"{model}_{size}" if size else model


def _marker_for_label(label: str) -> str:
    s = label.lower()
    if "gemma3" in s:
        return "s"  # square
    if "gemma4" in s:
        return "^"  # triangle
    return "o"  # default dot


def _line_style_for_label(label: str) -> dict:
    s = label.lower()
    if "gemma3" in s or "gemma4" in s:
        return {
            "linewidth": 3.0,
            "markersize": 7.5,
            "markeredgewidth": 1.2,
            "markeredgecolor": "black",
            "zorder": 5,
        }
    return {
        "linewidth": 2.0,
        "markersize": 5.0,
        "markeredgewidth": 0.0,
        "zorder": 2,
    }


def main() -> int:
    args = parse_args()
    report_path = args.report_json.resolve()
    output_path = args.output.resolve()

    if not report_path.exists():
        raise FileNotFoundError(f"Report JSON not found: {report_path}")

    payload = json.loads(report_path.read_text(encoding="utf-8"))
    by_model = payload.get("by_model", {})
    if not by_model:
        raise RuntimeError("No by_model data found in report JSON.")

    model_series: list[tuple[str, dict[str, float]]] = []
    all_tasks: set[str] = set()

    for _, info in sorted(by_model.items()):
        task_stats = info.get("task_stats", {})
        if not isinstance(task_stats, dict):
            continue
        task_means: dict[str, float] = {}
        for task_id, stats in task_stats.items():
            mean_value = stats.get("mean")
            if isinstance(mean_value, (int, float)):
                task_means[task_id] = float(mean_value)
        if len(task_means) < args.min_tasks:
            continue
        label = _model_label(str(info.get("model", "")), info.get("size"))
        model_series.append((label, task_means))
        all_tasks.update(task_means.keys())

    if not model_series:
        raise RuntimeError("No model series matched filters.")

    tasks = sorted(all_tasks, key=_task_sort_key)
    x = list(range(len(tasks)))

    fig, ax = plt.subplots(figsize=(max(10, len(tasks) * 1.6), 6))
    for label, task_means in model_series:
        y = [task_means.get(task_id, float("nan")) for task_id in tasks]
        style = _line_style_for_label(label)
        ax.plot(
            x,
            y,
            marker=_marker_for_label(label),
            label=label,
            linewidth=style["linewidth"],
            markersize=style["markersize"],
            markeredgewidth=style["markeredgewidth"],
            markeredgecolor=style.get("markeredgecolor"),
            zorder=style["zorder"],
        )

    ax.set_title("Model Accuracy by Task")
    ax.set_xlabel("Task")
    ax.set_ylabel("Accuracy")
    ax.set_xticks(x)
    ax.set_xticklabels(tasks, rotation=25, ha="right")
    ax.set_ylim(0.0, 1.0)
    ax.grid(True, axis="y", alpha=0.3)
    ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=False)
    fig.tight_layout()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=160, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

